-- Generated by tools/generate-archives.mjs
SET NAMES utf8mb4;
USE db_rw;

CREATE TABLE IF NOT EXISTS archives (
  value CHAR(7)     NOT NULL PRIMARY KEY,  -- e.g. 2026-09
  label VARCHAR(30) NOT NULL               -- e.g. September 2026
);

INSERT IGNORE INTO archives (value, label) VALUES
  ('2026-09', 'September 2026'),
  ('2025-08', 'August 2025'),
  ('2024-09', 'September 2024'),
  ('2023-09', 'September 2023'),
  ('2022-12', 'December 2022'),
  ('2022-08', 'August 2022'),
  ('2022-07', 'July 2022'),
  ('2021-08', 'August 2021'),
  ('2020-02', 'February 2020'),
  ('2019-02', 'February 2019'),
  ('2018-10', 'October 2018'),
  ('2018-08', 'August 2018'),
  ('2018-04', 'April 2018'),
  ('2018-03', 'March 2018'),
  ('2018-02', 'February 2018'),
  ('2018-01', 'January 2018'),
  ('2017-12', 'December 2017'),
  ('2017-04', 'April 2017'),
  ('2016-12', 'December 2016'),
  ('2015-07', 'July 2015'),
  ('2015-06', 'June 2015');
