/**
 * Converts src/data/posts.js into seed.sql (and optionally copies the images).
 *
 * Run from the ROOT of your Vite project:
 *   node tools/generate-seed.mjs "C:/xampp/htdocs/RW_LAUS/backend/uploads"
 *
 * Output: seed.sql in the current folder -> import it in phpMyAdmin (db_rw > Import).
 */
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { pathToFileURL } from "node:url";

const POSTS_FILE = path.resolve("src/data/posts.js");
const IMAGES_DIR = path.resolve("src/assets/images");
const OUT_FILE = path.resolve("seed.sql");
const uploadsDest = process.argv[2] ? path.resolve(process.argv[2]) : null;

// 1) Turn the image imports into plain strings ("page1/file.png") so Node can load the module.
let src = fs.readFileSync(POSTS_FILE, "utf8");
const importRe = /import\s+(\w+)\s+from\s+["']\.\.\/assets\/images\/([^"']+)["'];?/g;
const usedFiles = new Set();
src = src.replace(importRe, (_m, name, file) => {
  usedFiles.add(file);
  return `const ${name} = ${JSON.stringify(file)};`;
});

// 2) Load the transformed module from a temp file.
const tmp = path.join(os.tmpdir(), `rw-posts-${Date.now()}.mjs`);
fs.writeFileSync(tmp, src);
let mod;
try {
  mod = await import(pathToFileURL(tmp).href);
} finally {
  fs.unlinkSync(tmp);
}
const { posts } = mod;

// 3) Build SQL.
const q = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return (
    "'" +
    String(v)
      .replace(/\\/g, "\\\\")
      .replace(/'/g, "\\'")
      .replace(/\r/g, "\\r")
      .replace(/\n/g, "\\n") +
    "'"
  );
};
const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const lines = [
  "-- Generated by tools/generate-seed.mjs",
  "SET NAMES utf8mb4;",
  "USE db_rw;",
  "",
  "-- Make the script safe to re-run",
  "SET FOREIGN_KEY_CHECKS = 0;",
  "TRUNCATE TABLE post_images;",
  "TRUNCATE TABLE post_categories;",
  "TRUNCATE TABLE posts;",
  "SET FOREIGN_KEY_CHECKS = 1;",
  "",
  "INSERT IGNORE INTO categories (name, slug) VALUES ('Events','events'),('News','news'),('Uncategorized','uncategorized');",
  "",
];

posts.forEach((p, i) => {
  const byline = p.bylineLines ? p.bylineLines.join("\n") : p.byline ?? null;
  const cols = [
    "slug", "title", "excerpt", "byline", "byline_italic", "show_title_above_byline",
    "about_writer", "body", "featured_image", "gallery_columns", "gallery_count",
    "published_at", "sort_order",
  ];
  const vals = [
    q(p.slug), q(p.title), q(p.excerpt ?? null), q(byline),
    p.bylineItalic ? 1 : 0, p.showTitleAboveByline ? 1 : 0,
    q(p.aboutWriter ?? null), q(JSON.stringify(p.body ?? [])),
    q(p.image ?? null), q(p.galleryColumns ?? null), p.galleryCount ?? 0,
    q(p.date ?? null), i,
  ];
  lines.push(`INSERT INTO posts (${cols.join(", ")}) VALUES (${vals.join(", ")});`);
  for (const c of p.categories ?? []) {
    lines.push(
      `INSERT INTO post_categories (post_id, category_id) SELECT p.id, c.id FROM posts p, categories c WHERE p.slug = ${q(p.slug)} AND c.slug = ${q(slugify(c))};`
    );
  }
  lines.push("");
});

fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf8");
console.log(`Wrote ${OUT_FILE} (${posts.length} posts, ${usedFiles.size} featured images)`);

// 4) Optionally copy images so filenames in the DB match files on disk 1:1.
if (uploadsDest) {
  fs.cpSync(IMAGES_DIR, uploadsDest, { recursive: true });
  console.log(`Copied images -> ${uploadsDest}`);
}   